sudo: false
language: ruby
cache:
  bundler: true
  directories:
    - node_modules
rvm:
- 2.2
script: bundle exec jekyll build && bundle exec htmlproof ./_site --href-swap "https?\W{1}\/\/developers\.shipcloud\.io":""
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_install:
  - npm list firebase-tools --depth=0 || npm install firebase-tools
deploy:
  provider: script
  script: firebase deploy --token "$FIREBASE_TOKEN"
  on:
    repo: shipcloud/shipcloud.github.io
    branch: master
  skip_cleanup: true
notifications:
  flowdock:
    secure: fSZxX5z3bHWT8aCFKBFrDDt5o3Jb6EFWcm+pAcMabpfDHc4iktWuCUlSM405798TRdKdws1A2RncQGYiQyLbqNvtLz48dvj4BxgYW7P/vg0koN+I/H2MjpZeuIQ7BRSEJIq2sAYNVya+hSil+SPEBMTngJiP6VYG0dm6fFnRkyk=
