sudo: false
language: ruby
cache:
  bundler: true
  directories:
    - node_modules
rvm:
- 2.2
script: bundle exec jekyll build && bundle exec htmlproof ./_site --href-swap "https?\W{1}\/\/developers\.shipcloud\.io":""
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_install:
  - npm list firebase-tools --depth=0 || npm install firebase-tools
deploy:
  provider: script
  script: firebase deploy --token "$FIREBASE_TOKEN"
  on:
    repo: shipcloud/shipcloud.github.io
    branch: master
  skip_cleanup: true
